layout_spectrum: 0.6331667
typography_spectrum: 0.9754609
color:
  saturation: 0.8298117
  lightness: 0.7361773
  brandStrength: 0.02819549
  brandColors:
    - '#09060A'
    - '#EBE3C9'
    - '#5E5A51'
    - '#79A3BC'
    - '#EF0D37'
  rhythmicContrast: 0.2038941
name: Mbs4life
